# Permalinks
permalink:      /:title

# Setup
title:          Web Scraper User Guide
paginate:       5
baseurl:        "/wrd204"
url:            "https://tjgambs.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# Gems
gems:
  - jekyll-paginate
